wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.13
    t:
      1:
      - 5
      4: 3.6.13
      5: 0.10.32
      8:
      - 1
      - 3
      - 5
